variables:
  NODEJS_PIPELINE_IMAGE: 'node:22.15.0-alpine3.21'
  NODEJS_IMAGE: 'node:22.15.0-alpine3.21'
include:
  - project: 'telecom-argentina/coo/fintech/devops/cicd-regional'
    ref: master
    file:
      - '/03.typescript-rest/.00-main.yml'
